name: Build Pipeline
on:
  push:
    branches:
      - master
    paths:
      - 'resume.json'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install json-resume cli
        run: npm install -g resume-cli

      - name: Install themes
        run: npm install jsonresume-theme-macchiato-ibic

      - name: Make resumes
        run: make build

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            html/*
            pdf/*
            index.html
          commit-msg: Update resources
          github-token: ${{ secrets.GITHUB_TOKEN }}