name: Building New Resume
on:
  push:
    branches:
      - master
    paths:
      - 'resume.json'
      # - '.github/workflows/build_resume.yaml'
      # - 'Makefile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit == false }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install -g resume-cli

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit == 'true'
        run: npm install

      - name: Build
        run: npm build

      - name: Test
        run: npm test
      
      - name: Build resume
        run:  make resume

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            html/resume_marco_acea.html
            pdf/resume_marco_acea.pdf
            index.html
            package-lock.json
          commit-msg: Update resources
          github-token: ${{ secrets.GITHUB_TOKEN }}
