name: Building New Experimental Resume
on:
  push:
    branches:
      - dev
    paths:
      - 'resume.json'
      - '.github/workflows/build_dev_resume.yaml'
      - 'Makefile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'dev'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # - name: Cache node modules
      #   id: cache-npm
      #   uses: actions/cache@v3
      #   env:
      #     cache-name: cache-node-modules
      #   with:
      #     # npm cache files are stored in `~/.npm` on Linux/macOS
      #     path: ~/.npm
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-${{ env.cache-name }}-
      #       ${{ runner.os }}-build-
      #       ${{ runner.os }}-

      - name: Install dependencies if package-lock file was not found
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm i -g resume-cli
          npm i jsonresume-theme-macchiato-ibic

      # - if: ${{ steps.cache-npm.outputs.cache-hit == false }}
      #   name: List the state of node modules
      #   continue-on-error: true
      #   run: npm list

      # - name: Install Dependencies if cache not found
      #   if: steps.cache.outputs.cache-hit != 'true'
      #   continue-on-error: false
      #   run: |
      #     pwd
      #     ls -a
      #     chmod +x "./install.sh"
      #     ./install.sh

      # - name: Install dependencies
      #   run: |
      #     npm install
      #     npm build
      #     npm test

      # - name: Install dependencies
      #   run: npm ci --ignore-scripts

      - name: Build recent resumes
        continue-on-error: true
        run: |
          resume export --theme=jsonresume-theme-macchiato-ibic resume.pdf
          resume export --theme=jsonresume-theme-macchiato-ibic resume.html
          mv resume.html index.html
      
      # - name: Build resume
      #   run:  make resume

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            resume.pdf
            index.html
            package-lock.json
          commit-msg: Update resources
          github-token: ${{ secrets.GITHUB_TOKEN }}
